### ISSUE TITLE
Documentation bug -   waitForIsNotVisible(); waitIsVisible();

### ISSUE THREAD

**Issue by chrberSTO** [telekom/testerra#86]
**Describe the bug**

This description is not sufficient to actually understand

    /**
     * Wait till element is not visible within the viewport (--> What does the boolean parameter do?)
     */
    boolean waitForIsVisible(final boolean complete);

    /**
     * Wait till element is not more visible within the viewport
     */
    boolean waitForIsNotVisible();

**To Reproduce**
Look at 1.0-RC-32 eu/tsystems/mms/tic/testframework/pageobjects/internal/waiters/GuiElementWait.java

**Expected behavior**
Clear documentation on what the parameters do in this context and what the different methods actually do. There is also no documentation here: http://docs.testerra.io/testerra/1.0-RC-23/#_create_a_new_project

**Environment(please complete the following information):**
 - OS: MacOS
 - Browser n/a
 - Version 1.0-RC-32

**Additional context**
I have a problem that the following code does not get me a click in the TAP:

cartLink.asserts().assertIsDisplayed();
cartLink.click();

https://tapbs01.t-systems-mms.eu/repository/download/STOcep_STOcepTesterraConfigChromeNightly/548676:id/test-report/report-ng/index.html#/method/60decb1e7da0effbc6056bfc/details I am trying to find a way to make my test more rubust and thought waitForIsVisible(); could help, but I do not understand how to use it.

**Comment by mreiche** [comment]
I've updated the documentation: `waitForIsVisible()` or `assertVisible()` just does element visibility checks based on intersections of its bounding box and the view port. Usually, `assertIsDisplayed()` just determines if an element is displayed generally but not if its visible. Anyway, your root cause `ElementClickInterceptedException` is based on something else.

- Is your element visible to you?
- Is the element interactable or disabled?
- Is there another element overlapping this element?
- Can you `highlight()` the element?
- Is your element part of a shadow root?

**Comment by chrberSTO** [comment]
The problem lies in a logic on the page, the element exists twice and I have not found a way to check through code, when which of them is visible.

Please see below:

When you scroll:

The element actually exists twice: 

 
Is your element visible to you?
To me yes, but the method not:

 
Is the element interactable or disabled?
 

I solved it like that, but it really seems wrong to do It like that:

cartLink.getList().get(0).isSelectable();

cartLink.getList().get(1).isSelectable();
Is there another element overlapping this element?
Can you highlight() the element?
I can highlight both

cartLink.getList().get(0).highlight();

cartLink.getList().get(1).highlight();
Is your element part of a shadow root?

**Comment by chrberSTO** [comment]
Ah, the mail had screenshots, they were not taken over

**Comment by chrberSTO** [comment]
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/80685133/124286452-41eecb00-db4f-11eb-8540-f7d4aa61e228.png">

<img width="732" alt="image" src="https://user-images.githubusercontent.com/80685133/124286494-503ce700-db4f-11eb-92f3-53a4fa74d618.png">

<img width="729" alt="image" src="https://user-images.githubusercontent.com/80685133/124286523-5763f500-db4f-11eb-8d81-3bde7a02bc17.png">

<img width="421" alt="image" src="https://user-images.githubusercontent.com/80685133/124286545-5e8b0300-db4f-11eb-925d-da550631ece7.png">

**Comment by mreiche** [comment]
Ok, having 2 elements for the same selector, when you expecting actually only one can be managed in three ways:
- Using lists is what you did (not the best approach but intuitive)
- Another, way more elegant, way is to use `Locate` filters to select only elements that are displayed.
  ```java
  Locate myLocator = Locate.by(By.id("myId")).displayed();
  GuiElement guiElement = new GuiElement(WebDriver, myLocator);
  ```
- Or, if you want to fail when more than element has been found, use:
  ```java
  Locate myLocator = Locate.by(By.id("myId")).unique();
  GuiElement guiElement = new GuiElement(WebDriver, myLocator);
  ```

See also https://docs.testerra.io/testerra/stable/index.html#_locate_displayed_items_only

**Comment by chrberSTO** [comment]
Thank you Mike for the cool hint. However there is one problem, both elements have displayed as true, so there is no way to differentiate both of them

 

Any idea? Of course I could ask the developers to correct their mistake in the QA tag as this should not happen that one tag is used twice.

 

 

 

From: Mike Reiche ***@***.***>
Reply to: telekom/testerra ***@***.***>
Date: Friday, 2. July 2021 at 17:18
To: telekom/testerra ***@***.***>
Cc: chrberSTO ***@***.***>, Author ***@***.***>
Subject: Re: [telekom/testerra] Documentation bug - waitForIsNotVisible(); waitIsVisible(); (#86)

 

Ok, having 2 elements for the same selector, when you expecting actually only one can be managed in three ways:
Using lists is what you did (not the best approach but intuitive)
Another, way more elegant, way is to use Locate filters to select only elements that are displayed. 
·         Locate myLocator = Locate.by(By.id("myId")).displayed();
GuiElement guiElement = new GuiElement(WebDriver, myLocator);
Or, if you want to fail when more than element has been found, use: 
·         Locate myLocator = Locate.by(By.id("myId")).unique();
GuiElement guiElement = new GuiElement(WebDriver, myLocator);
See also https://docs.testerra.io/testerra/stable/index.html#_locate_displayed_items_only

**Comment by mreiche** [comment]
I don't see a better solution here except to break down the elements to components (e.a. Header, Footer, Body) you name it.

**Comment by chrberSTO** [comment]
Hi Mike,

the actual problem here is, that the isVisible() does not return what I would expect. 

If I see the basket link number 1 in the browser, I would expect the isVisible() to return true, but it does not:

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/80685133/124429378-1a297e00-dd6e-11eb-9d3a-82f39aaff1ee.png">

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/80685133/124429343-0da52580-dd6e-11eb-937a-dfd5c11113cd.png">

When the basket link number 2 is visible in the browser, I would expect the is visible to return true, but it does not either:

<img width="1835" alt="image" src="https://user-images.githubusercontent.com/80685133/124429535-4ba24980-dd6e-11eb-8d4b-f1ba2aa38083.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/80685133/124429639-6aa0db80-dd6e-11eb-828e-5c5b07b47842.png">

This is what I meant by, I can not differentiate between both elements. Sorry, I was not really clear on this. Do I have the wrong expectation there?

**Comment by chrberSTO** [comment]
Each elements is highlighted if I do a 

<img width="679" alt="image" src="https://user-images.githubusercontent.com/80685133/124430366-5dd0b780-dd6f-11eb-9373-42a038012a1f.png">

or

<img width="689" alt="image" src="https://user-images.githubusercontent.com/80685133/124430291-4691ca00-dd6f-11eb-8a24-f03b311181dd.png">

**Comment by mreiche** [comment]
I dont have access to check that on my side, but you could debug `DesktopGuiElementCore.isVisible()` and see if `WebElement.getLocation()` and `WebElement.getSize()` are valid.

**Comment by mreiche** [comment]
`isVisible()` is confirmed buggy and hopyfully fixed by https://github.com/telekom/testerra/pull/88 but I cannot confirm that now.

**Comment by mreiche** [comment]
@chrberSTO Please check if this bug is fixed by checking out the branch of this PR https://github.com/telekom/testerra/pull/88

1. When you are using gradle, just create an `settings.gradle` and use your local Testerra clone.
   ```groovy
   rootProject.name = 'your-project'
   includeBuild "../testerra"
   ```
2. When not, just compile it using `gradle clean publishToMavenLocal` and add change your dependency to `1-SNAPSHOT`

**Comment by martingrossmann** [comment]
I've deployed Testerra `1.5-SNAPSHOT`. Please add the repo `https://s01.oss.sonatype.org/content/repositories/snapshots/` to your Maven or Gradle config to use snapshots.

**Comment by chrberSTO** [comment]
Hi Martin,

 

I can confirm that 1.5-Snapshot works in terms of isVisible working again. I still have the problem that the isVisible returns false on the second GuiElement when it is visible, while a highlight actually highlights the element. I am not quite sure atm, if this is a problem in the DOM or with the framework. In any case, thank you for fixing this.

 

Is there a mailing list or some webpage where I can find information about the release schedule or get informed if a new release is available?

 

Thank you and  kind regards.

Christian

 

From: Martin Großmann ***@***.***>
Reply to: telekom/testerra ***@***.***>
Date: Tuesday, 6. July 2021 at 12:07
To: telekom/testerra ***@***.***>
Cc: chrberSTO ***@***.***>, Mention ***@***.***>
Subject: Re: [telekom/testerra] Documentation bug - waitForIsNotVisible(); waitIsVisible(); (#86)

 

I've deployed Testerra 1.5-SNAPSHOT. Please add the repo https://s01.oss.sonatype.org/content/repositories/snapshots/ to your Maven or Gradle config to use snapshots.

**Comment by martingrossmann** [comment]
@chrberSTO Unfortunately it seems Github does not support notifications for releases. And we do not have a mailing list or similar.

But Github supports feeds for releases: https://github.com/telekom/testerra/releases.atom. With an external RSS reader you can subscribe it and maybe there is a notification feature.

**Comment by mreiche** [comment]
Well, you still can check if `WebElement.getLocation()` and `WebElement.getSize()` are valid.

**Comment by chrberSTO** [comment]
Hi Mike,

both are shown:
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/80685133/124755964-44289f00-df2c-11eb-9db8-d9b349220d75.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/80685133/124756024-51de2480-df2c-11eb-90a1-16b6a3e2cb7d.png">

but isVisible still returns false:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/80685133/124756189-7afeb500-df2c-11eb-9839-1f09dd4c7126.png">

isDisplayed:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/80685133/124756279-92d63900-df2c-11eb-8c07-85c42cfb9c04.png">

highlight highlights the element.

**Comment by mreiche** [comment]
Are you sure that you are using `1.5-SNAPSHOT`?

**Comment by mreiche** [comment]
What does this mean exactly? The `isVisible()` works like expected and the bug is finally gone?

**Comment by chrberSTO** [comment]
By this I mean that in both cases the isVisible is working now, as before it was only working for one case:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/80685133/124908936-2de11880-dfea-11eb-840c-338d722a3ef3.png">

also when not visible this is working:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/80685133/124909022-43564280-dfea-11eb-8014-ea2979698b87.png">

when second is visble:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/80685133/124909114-5e28b700-dfea-11eb-90fb-814bfae5f246.png">


So yes, bug is gone. Thank you very much.
